name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: cross-wails-cd
  cancel-in-progress: true

jobs:
  publish:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: read
      packages: write
    with:
      PUSH_IMAGE: true
      GO_VERSION: "1.21.5"
      NODE_VERSION: "20"
      WAILS_VERSION: "v2.7.1"
